
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_design?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml